
export type Language = 'en' | 'pt';

export const getSystemLanguage = (): Language => {
  const lang = navigator.language || 'en';
  return lang.startsWith('pt') ? 'pt' : 'en';
};

export const STRINGS = {
  en: {
    home: "Home",
    training: "Training",
    profile: "Profile",
    goodMorning: "Good Morning",
    streak: "Streak",
    coachTip: "Coach Tip",
    weeklyVolume: "Weekly Volume",
    recentActivity: "Recent Activity",
    startWorkout: "Start Workout",
    myRoutines: "My Routines",
    create: "Create",
    createNewRoutine: "Create New Routine",
    explore: "Explore",
    scientific: "Scientific",
    exercises: "Exercises",
    routineName: "Routine Name",
    placeholderRoutineName: "e.g. Leg Day Opener",
    save: "Save",
    finish: "Finish",
    skip: "Skip",
    rest: "Rest",
    sets: "Sets",
    reps: "Reps",
    time: "Time",
    min: "min",
    premiumOnly: "Premium Only",
    startRoutine: "Start Routine",
    checkSet: "Check Set",
    stopTimer: "Stop Timer & Rest",
    startTimer: "Start Timer",
    skipRest: "Skip Rest",
    skipExercise: "Skip Exercise",
    upgrade: "Upgrade Now",
    manageSubscription: "Manage Subscription",
    premiumStats: "Premium Stats",
    unlockStats: "Unlock monthly breakdowns and deep analytics.",
    premiumBenefits: "Unlimited routines, scientific plans, and advanced stats.",
    freeAccount: "Free Account",
    premiumMember: "Premium Member",
    workouts: "Workouts",
    minutes: "Minutes",
    consistency: "Consistency",
    devToggle: "[Dev: Toggle Premium Status]",
    loading: "Loading motivation...",
    noWorkouts: "No workouts yet. Start moving!",
    done: "Done",
    newRoutine: "New Routine",
    addSet: "Add Set",
    removeSet: "Remove Set",
    set: "Set",
    previous: "Previous",
    complete: "Complete",
    workoutSummary: "Workout Summary",
    totalTime: "Total Time",
    exercisesCompleted: "Exercises Completed",
    goodJob: "Good Job!",
    cancel: "Cancel",
    confirmFinish: "Finish Workout?",
    muscleGroups: {
      "Ankle": "Ankle",
      "Calf": "Calf",
      "Hamstrings": "Hamstrings",
      "Hips": "Hips",
      "Thoracic Spine": "Thoracic Spine",
      "Shoulder": "Shoulder",
      "Neck": "Neck",
      "Wrists": "Wrists",
      "Lower Back": "Lower Back",
      "Upper Back": "Upper Back",
      "Glutes": "Glutes",
      "Full Body": "Full Body"
    }
  },
  pt: {
    home: "Início",
    training: "Treino",
    profile: "Perfil",
    goodMorning: "Bom Dia",
    streak: "Sequência",
    coachTip: "Dica do Treinador",
    weeklyVolume: "Volume Semanal",
    recentActivity: "Atividade Recente",
    startWorkout: "Iniciar Treino",
    myRoutines: "Minhas Rotinas",
    create: "Criar",
    createNewRoutine: "Criar Nova Rotina",
    explore: "Explorar",
    scientific: "Científico",
    exercises: "Exercícios",
    routineName: "Nome da Rotina",
    placeholderRoutineName: "ex: Aquecimento de Pernas",
    save: "Salvar",
    finish: "Finalizar",
    skip: "Pular",
    rest: "Descanso",
    sets: "Séries",
    reps: "Reps",
    time: "Tempo",
    min: "min",
    premiumOnly: "Apenas Premium",
    startRoutine: "Começar Rotina",
    checkSet: "Concluir Série",
    stopTimer: "Parar e Descansar",
    startTimer: "Iniciar Timer",
    skipRest: "Pular Descanso",
    skipExercise: "Pular Exercício",
    upgrade: "Assinar Agora",
    manageSubscription: "Gerenciar Assinatura",
    premiumStats: "Estatísticas Premium",
    unlockStats: "Desbloqueie análises mensais e detalhadas.",
    premiumBenefits: "Rotinas ilimitadas, planos científicos e estatísticas avançadas.",
    freeAccount: "Conta Grátis",
    premiumMember: "Membro Premium",
    workouts: "Treinos",
    minutes: "Minutos",
    consistency: "Consistência",
    devToggle: "[Dev: Alternar Status Premium]",
    loading: "Carregando motivação...",
    noWorkouts: "Sem treinos ainda. Comece a se mover!",
    done: "Feito",
    newRoutine: "Nova Rotina",
    addSet: "Adicionar Série",
    removeSet: "Remover Série",
    set: "Série",
    previous: "Anterior",
    complete: "Concluir",
    workoutSummary: "Resumo do Treino",
    totalTime: "Tempo Total",
    exercisesCompleted: "Exercícios Concluídos",
    goodJob: "Bom Trabalho!",
    cancel: "Cancelar",
    confirmFinish: "Finalizar Treino?",
    muscleGroups: {
      "Ankle": "Tornozelo",
      "Calf": "Panturrilha",
      "Hamstrings": "Isquiotibiais",
      "Hips": "Quadris",
      "Thoracic Spine": "Coluna Torácica",
      "Shoulder": "Ombros",
      "Neck": "Pescoço",
      "Wrists": "Punhos",
      "Lower Back": "Lombar",
      "Upper Back": "Costas Sup.",
      "Glutes": "Glúteos",
      "Full Body": "Corpo Todo"
    }
  }
};
